# Generated by Django 3.1.5 on 2021-01-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_hashed_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hashed_id',
            field=models.CharField(blank=True, default='9bf1960638b44dda', max_length=16, null=True, unique=True),
        ),
    ]
