# Generated by Django 3.1.5 on 2021-01-24 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_activitylog_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='resource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resource_permission', to='account.resource'),
            preserve_default=False,
        ),
    ]
