# Generated by Django 3.1.5 on 2021-01-29 14:58

import apps.core.account.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_permission_resource'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.core.account.manager.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
