# Generated by Django 3.1.5 on 2021-01-22 02:40

import apps.core.base.utils.basics
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='hashed_id',
            field=models.CharField(blank=True, default=apps.core.base.utils.basics.random_hex_code, max_length=16, null=True, unique=True),
        ),
    ]
