# Generated by Django 3.1.5 on 2021-02-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20210217_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(1, 'Multiple Choice'), (2, 'Descriptive')], default=1),
        ),
    ]
