# Generated by Django 3.1.5 on 2021-02-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='total_mark',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='correct_mark',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='exam',
            name='wrong_mark',
            field=models.FloatField(default=0),
        ),
    ]
