# Generated by Django 3.1.5 on 2021-01-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20210122_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='hashed_id',
            field=models.CharField(blank=True, default='3045674c07864441', max_length=16, null=True, unique=True),
        ),
    ]
