# Generated by Django 3.1.5 on 2021-01-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20210122_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='hashed_id',
            field=models.CharField(blank=True, default='41a1d46532404942', max_length=16, null=True, unique=True),
        ),
    ]
