# Generated by Django 3.1.5 on 2021-02-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20210217_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_duration',
            field=models.IntegerField(help_text='Time in minute'),
        ),
    ]
